Все пять задач из первого урока
js-tasks-ru/jsbasic-20230116-2_arinoko99 pull request #2
Opened 2023-01-22 06:13 UTC by gerdas-ari

2023-01-22 06:14 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-01-22 06:19 UTC, gerdas-ari commented
Я первое задание сама решила, уже после захотела посмотреть решение, и он мне автоматически засчитал его. Я сама решала...

2023-01-23 15:55 UTC, SinimaWath requested changes
У тебя теперь появился конфликт: Есть решенная задача (та которую подсмотрела) в upstream и в origin

Сделай:
- `git pull upstream master`

 - Пофикси конфликт, убери в файлике разделители `=====` `<===` и т,д. Если их нет, переходи к след шагу
 
 - Сделай коммит и запушь
 
 
 Вот тут хороший пример: https://www.youtube.com/watch?v=PXK1hIifpWU

2023-01-23 15:55 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
`return name != null && name != "" && name.length >= 4 && !name.includes(" ")` - если результат операции boolean, то if не нужен

2023-01-23 15:55 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  }
`return strLow.includes('1xbet') || strLow.includes('xxx')`

2023-01-24 09:37 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-01-24 09:39 UTC, gerdas-ari commented on 1-module/4-task/index.js
> +  }
Если после своего решения задачи и после прохождения всех тестов успешно я хочу посмотреть эталонное решение, как это сделать без доп слияний и конфликтов?

2023-01-24 09:40 UTC, gerdas-ari commented
Если после своего решения задачи и после прохождения всех тестов успешно я хочу посмотреть эталонное решение, как это сделать без доп слияний и конфликтов?

2023-01-24 11:13 UTC, SinimaWath approved these changes
Посмотреть решения, можно после того как волью твой ПР. В отдельной ветке:
`solutions`

2023-01-24 11:14 UTC, merged

2023-01-24 11:32 UTC, gerdas-ari commented
Поняла, спасибо!)